# 错误代码定义和常量

ERR_INVALID_PATH = 1
ERR_ALREADY_EXISTS = 2
ERR_NOT_FOUND = 3
ERR_INVALID_OPERATION = 4
ERR_IO_ERROR = 5
ERR_INVALID_PACKET = 6
ERR_TIMEOUT = 7

PACKET_HEADER = b"\x54\x32"
PACKET_TAIL = b"\x23\x45"

PACKET_MAX_SIZE = 3072
PACKET_MIN_SIZE = 10
